apiVersion: apps/v1
kind: Deployment
metadata:
  name: bmi-frontend
  namespace: bmi-app
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bmi-frontend
  template:
    metadata:
      labels:
        app: bmi-frontend
    spec:
      containers:
        - name: bmi-frontend
<<<<<<< HEAD
          image: 014882039467.dkr.ecr.ap-south-1.amazonaws.com/bmi-frontend:5e065bc
=======
          image: 014882039467.dkr.ecr.ap-south-1.amazonaws.com/bmi-frontend:latest
>>>>>>> 6e258475060f35aad82300d63bd43e9769a5fb87
          imagePullPolicy: Always
          ports:
            - containerPort: 80

          resources:
            requests:
              cpu:    "50m"
              memory: "64Mi"
            limits:
              cpu:    "200m"
              memory: "128Mi"

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds:       30
            timeoutSeconds:      5

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds:       10
            timeoutSeconds:      5
      imagePullSecrets:
        - name: ecr-credentials
